stations:  # Use https://transport.opendata.ch/examples/stationboard.html to find the name of the station
  - Zürich, Oberwiesenstrasse
  - Zürich, Neuaffoltern
  - Zürich, Chaletweg

#links_whitelist: [BUS32, BUS61, BUS62]
