# Use https://transport.opendata.ch/examples/stationboard.html to find station names
connections:
  - from: Zürich, Oberwiesenstrasse
    to:   Zürich, ETH/Universitätsspital
  - from: Zürich, Neuaffoltern
    to:   Zürich, Militär-/Langstrasse

# Not implemented yet:
#links_whitelist: [BUS 32, BUS 61, BUS 62]
